name: Deploy Azure VM

on:
  push:
    branches: [ mains ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create env
      env:
        CI_SSH_KEY: ${{ secrets.CI_SSH_KEY }}
      run: |
        echo -e "$CI_SSH_KEY" > id_rsa.txt
    - name: Deploy
      env:
        CI_DEV_SSH_USER: ${{ secrets.CI_DEV_SSH_USER }}
        CI_DEV_SSH_HOST: ${{ secrets.CI_DEV_SSH_HOST }}
      run: |
        rsync -ahrz --exclude-from '.dockerignore' -e "sudo ssh -i id_rsa.txt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./ $CI_DEV_SSH_USER@$CI_DEV_SSH_HOST:aift-ai
        sudo ssh -i id_rsa.txt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $CI_DEV_SSH_USER@$CI_DEV_SSH_HOST "cd aift-ai && sudo docker build -t aift-ai . && sudo docker run -it --name aift_ai_container -p 50051:50051 -d aift-ai"
